name: pronz
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rounded_date_picker:
  carousel_slider:
  flutter_cupertino_date_picker:
  toggle_switch:
  persistent_bottom_nav_bar:
  ff_navigation_bar:
  community_material_icon:
  outline_material_icons:
  url_launcher:
  location: ^4.0.0
  geolocator:
  geocoder:
  path_provider:
  path:
  image:
  image_picker:
  font_awesome_flutter:
  rxdart: any
  google_maps_flutter: ^0.5.11+1
  file_picker: ^1.4.0+1
  emoji_picker: ^0.0.2

  flutter_downloader: ^1.2.2
  downloads_path_provider: ^0.1.0
  flushbar: ^1.9.0
  connectivity: ^3.0.6
 # audio_recorder:
  #  geoflutterfire: ^2.0.3+2
      #  geoflutterfire: ^2.0.3+2


  google_maps_webservice: ^0.0.14
  shared_preferences :
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  animations: ^2.0.0
  like_button: ^2.0.2
  provider:
  firebase_auth: ^1.0.3
  google_sign_in:
  firebase_core: ^1.0.3
  http:
  flutter_facebook_login:
  flutter_spinkit:
  flutter_staggered_animations: "^0.1.2"
  decimal:
  splashscreen:
  #flutter_sound:
  flutter_phoenix:
  cloud_firestore:




  permission_handler: ^8.1.1
  #audio_recorder: ^1.0.2
  #flutter_audio_recorder: ^0.5.5
  #audioplayers:
  #audio_recorder2:
  random_string:
  video_player: ^0.10.1
  chewie: ^0.10.4

  #assets_audio_player:

  flutter_audio_query:
  audio_manager:
  flutter_native_image: ^0.0.6
  firebase_messaging: ^10.0.1
  flutter_local_notifications:
  pull_to_refresh:
  flutter_html:
  record_mp3:
  flutter_data_stream_builder:
  hashtagable: ^1.0.5+1
  linkable: ^1.0.4
  ffi: ^1.0.0
  easy_localization: ^3.0.0
  awesome_dialog: ^2.1.0
  timeago:
  intl:



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - audio/
    - assets/translations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
